export const gdgCountryMapping = {
    "GDG 臺北":"臺北",
    "GDG Cloud 臺北":"臺北",
    "GDG 新北":"新北",
    "GDG Cloud 新北":"新北",
    "GDG 桃園":"桃園",
    "GDG Cloud 桃園":"桃園",
    "GDG 新竹":"新竹", 
    "GDG 臺中":"臺中",
    "GDG Cloud 臺中":"臺中",
    "GDG 彰化":"彰化",
    "GDG Cloud 彰化":"彰化",
    "GDG 南投":"南投",
    "GDG Cloud 南投":"南投",
    "GDG 雲林":"雲林",
    "GDG Cloud 雲林":"雲林",
    "GDG 嘉義":"嘉義",
    "GDG Cloud 嘉義":"嘉義",
    "GDG 屏東":"屏東",
    "GDG Cloud 屏東":"屏東",
    "GDG 臺南":"臺南",
    "GDG Cloud 臺南":"臺南",
    "GDG 高雄":"高雄",
    "GDG Cloud 高雄":"高雄",
    "GDG 基隆":"基隆",
    "GDG Cloud 基隆":"基隆",
    "GDG 花蓮":"花蓮",
    "GDG Cloud 花蓮":"花蓮",
    "GDG 宜蘭":"宜蘭",
    "GDG Cloud 宜蘭":"宜蘭",
    "GDG 金門":"金門",
    "GDG Cloud 金門":"金門",
    "GDG 澎湖":"澎湖",
    "GDG Cloud 澎湖":"澎湖",
    "GDG 連江":"連江",
    "GDG Cloud 連江":"連江"
}