export const gdgNameMap = {
  'GDG Taipei': "GDG 臺北",
  'GDG Cloud Taipei': "GDG Cloud 臺北",
  'GDG Taoyuan': "GDG 桃園",
  'GDG Cloud Taoyuan': "GDG Cloud 桃園",
  'GDG Hsinchu': "GDG 新竹",
  'GDG Cloud Hsinchu': "GDG Cloud 新竹",
  'GDG Taichung': "GDG 臺中",
  'GDG Cloud Taichung': "GDG Cloud 臺中",
  'GDG Changhua': "GDG 彰化",
  'GDG Cloud Changhua': "GDG Cloud 彰化",
  'GDG Nantou': "GDG 南投",
  'GDG Cloud Nantou': "GDG Cloud 南投",
  'GDG Yunlin': "GDG 雲林",
  'GDG Cloud Yunlin': "GDG Cloud 雲林",
  'GDG Chiayi': "GDG 嘉義",
  'GDG Cloud Chiayi': "GDG Cloud 嘉義",
  'GDG Pingtung': "GDG 屏東",
  'GDG Cloud Pingtung': "GDG Cloud 屏東",
  'GDG Tainan': "GDG 臺南",
  'GDG Cloud Tainan': "GDG Cloud 臺南",
  'GDG Kaohsiung': "GDG 高雄",
  'GDG Cloud Kaohsiung': "GDG Cloud 高雄",
  'GDG Keelung': "GDG 基隆",
  'GDG Cloud Keelung': "GDG Cloud 基隆",
  'GDG Hualien': "GDG 花蓮",
  'GDG Cloud Hualien': "GDG Cloud 花蓮",
  'GDG Yilan': "GDG 宜蘭",
  'GDG Cloud Yilan': "GDG Cloud 宜蘭",
  'GDG Kinmen': "GDG 金門",
  'GDG Cloud Kinmen': "GDG Cloud 金門",
  'GDG Penghu': "GDG 澎湖",
  'GDG Cloud Penghu': "GDG Cloud 澎湖",
  'GDG Lienchiang': "GDG 連江",
  'GDG Cloud Lienchiang': "GDG Cloud 連江"
}