export const eventTagMap ={
    "Google I/O Extended": "Google I/O Extended",
    "Accessibility": "無障礙設計",
    "AI": "人工智慧",
    "Android": "Android",
    "Android Study Jam": "Android 學習營",
    "Career Development": "生涯規劃",
    "Certification Prep": "證書準備",
    "Ads/Traffic Analytics": "廣告/流量分析",
    "AR/VR": "擴增實境/虛擬實境",
    "Certification Study Group": "證書讀書會",
    "Cloud": "雲端",
    "Cloud Hero": "Cloud Hero",
    "Enterprise/Business Solutions": "企業/商業解決方案",
    "Cloud Study Jam": "雲端學習營",
    "Coding Challenge": "程式設計挑戰",
    "Community Building": "社群營造",
    "Compose Camp": "Compose Camp",
    "Data": "資料",
    "Design": "設計",
    "DevFest": "DevFest",
    "DevOps": "開發運維",
    "Firebase": "Firebase",
    "Flutter": "Flutter",
    "Google Assistant": "Google 助理",
    "Google Cloud Next": "Google Cloud Next",
    "Google Maps Platform": "Google 地圖平台",
    "Hash Code": "Hash Code",
    "International Women's Day": "國際婦女節",
    "IoT": "物聯網",
    "Inclusion": "多元融合",
    "JAX": "JAX",
    "Kaggle": "Kaggle",
    "Machine Learning": "機器學習",
    "Mobile": "行動裝置",
    "Networking": "網路通訊",
    "Road to Google Developers Certification": "通往 Google 開發者證書之路",
    "TensorFlow": "TensorFlow",
    "TensorFlow Extended": "TensorFlow Extended",
    "TensorFlow js": "TensorFlow.js",
    "Tensor Processing Unit": "Tensor 處理單元",
    "Web": "網頁",
    "Women Techmakers": "Women Techmakers",
    "Career Fair": "職業博覽會",
    "Angular": "Angular",
    "Next": "Next"
}